### ISSUE TITLE
Is merging method definitions possible?

### ISSUE THREAD

**Issue by jlperla** [chakravala/ForceImport.jl#1]
This is a step forward for sure.  My question is whether there is a way to have `@force` work with definitions of methods, merging into whichever function may currently be defined, even outside of modules (which makes jupyter/etc. easier to work with)

This would mean that the following would work
```
struct A
end
@force solve(a::A) = 1
```
But then if I changed my sourcecode to use something defining `solve` on unrelated types at the top, it wouldnt' break my definitions.  That is,
```
using DifferentialEquations
struct A
end
@force solve(a::A) = 1
```

similarly it would make it easy to tell people how to get around conflicts with names in Base.  That is,
```
struct A
end
@force function length(a::A)
   return 1
end

```

Any hope?

**Comment by chakravala** [comment]
I believe what you are trying to accomplish is already possible, if I understand correctly.

You could just do `@force using DifferentialEquations` or `@force using Base` and any exported names will be imported automatically, then you dont have to worry about whether you bothered to import any methods from it, since they all are, if thats what you wanted.
```Julia
julia> module stuff
           export hey
           hey(s::Int) = 2
       end
stuff

julia> @force using stuff

julia> hey(s::String) = "hey"
hey (generic function with 2 methods)

julia> hey("hi")
"hey"

julia> hey(1)
2
```
So if you have some code where you define `length` as a new method, and then you decide you want to extend methods from base, you can just add `@force using Base` or `import Base: length` at the top of your code. However, note that if you do `@force using Base`, you will import all `Base` methods that are exported, so any `Base` methods you make a new definition for will be extended. If you want to be more selective about which methods you want to extend, I recommend using `import` statements instead.

**Comment by jlperla** [comment]
I think I see, but it is a much bigger sledge hammer.  I guess my perspective is wondering if it is possible to put the onus on the method itself to merge with whatever is there.  This it is local to the method, as opposed to something which could have all sorts of side effects on the whole import of differential equations (i.e., I may only want to merge into a single function).  Much more of a localized change than the full merge, which is kind of scary!

The idea is that when training users (especially from single-dispatch) that get confused why they suddenly can't call methods what they want, we can train them that if that ever happens they can usually just throw in a `@force` in front and it will merge it into whatever function is there.  This can lead to code which is much less fragile.

We put in the documentation that this is also caveat emptor and just formalizes mild type-piracy.

**Comment by chakravala** [comment]
This would be a separate macro, perhaps `@merge` or something.

I think it's theoretically feasible, if I get around to it I will give it a shot and add it here, but you are also welcome to make a pull-request.

**Comment by jlperla** [comment]
Yeah, I think it would be separate.  `@forcemerge` or something.  If I find anyone competent enough to handle it, I will point them towards this as a project.  I, personally, I think that both that and `@force` belong in the standard library.

**Comment by chakravala** [comment]
The `master` branch now does have a `@merge` macro which does what you requested. However, it is required to call the `eval` method on the output of the macro, since code generation cannot be done with macros but should be done with `eval` instead. Here is an example:
```Julia
julia> using ForceImport

julia> module Mod
           export fun
           fun(x) = x
       end
Mod

julia> using Mod

julia> eval(@merge fun(x::String) = String)
fun (generic function with 2 methods)

julia> fun(1)
1

julia> fun("1")
String
```
So with the `eval(@merge fun...)` macro, the `Mod.fun` method is automatically imported if necessary.

**Comment by jlperla** [comment]
Thanks so much for this. I am curious if the core developers have any thoughts on making this sort of thing possible without an eval. Looks like it might take some witchcraft to make it more practical for newbie users.
